-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5bf6c09bfa1297d3692cadd621ef95f1284e33c0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: flake8
        exclude: docs/conf.py
    -   id: check-yaml
    -   id: check-merge-conflict
-   repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    sha: v1.0.0
    hooks:
    -   id: rst-linter
